### PR TITLE
Ensure SSH keys are in place

### PR DESCRIPTION
**Pull request by decentral1se**
Closes https://github.com/dokku/ansible-dokku/issues/2.

Haven't tested this manually.

Hopefully #28 will help with this going forward.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Is this necessary now that 0.19.5 is out?

**Comment by decentral1se** [comment]
I don't know, did you fix this in 0.19.5? Feel free to close if so.

**Comment by josegonzalez** [comment]
I think I did, but can you test?

**Comment by decentral1se** [comment]
I won't have time to chase this up but will close optimistically :+1:

**Comment by notapatch** [comment]
[@josegonzalez  - i have tested it and it now gives an error message](
https://github.com/dokku/ansible-dokku/issues/2) 👍 

Let me know if the issue requires any more testing.

**Pull request closed without merging**
