### PR TITLE
fix: drop support for outdated operating systems

### LINKED ISSUE #123: Latest version not available on Ansible Galaxy
## Description of problem

As of now, the latest version on Ansible Galaxy is v2021.9.5. Since that there were two releases.

### How reproducible

Always.

### Steps to Reproduce

1. Try to install v2021.11.7 with the following command: `ansible-galaxy role install dokku_bot.ansible_dokku,v2021.11.7`

#### Actual Results

```
Starting galaxy role install process
- downloading role 'ansible_dokku', owned by dokku_bot
[WARNING]: - dokku_bot.ansible_dokku was NOT installed successfully: - the
specified version (v2021.11.7) of dokku_bot.ansible_dokku was not found in the
list of available versions [...]
```

#### Expected Results

```
Starting galaxy role install process
- downloading role 'ansible_dokku', owned by dokku_bot
- downloading role from https://github.com/dokku/ansible-dokku/archive/v2021.11.7.tar.gz
- extracting dokku_bot.ansible_dokku to /builds/shiroi-usagi/builder/.ansible/roles/dokku_bot.ansible_dokku
- dokku_bot.ansible_dokku (v2021.11.7) was installed successfully
[...]
```

### `dokku report APP_NAME` output

-

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Dokku was installed via this ansible role on a physical machine and two DigitalOcean droplet.

### Additional information

See available versions on https://galaxy.ansible.com/dokku_bot/ansible_dokku

### PR DESCRIPTION
**Pull request by ltalirz**
On Ubuntu 16.04 the nginxinc.nginx roles fails with

  The repository 'https://nginx.org/packages/mainline/ubuntu xenial Release' does not have a Release file.

Seems like it's time to drop support; same for Debian 9.

Fixes #123 since all checks will be working again.

### CODE REVIEW

**Comment by ltalirz** [comment]
@josegonzalez This reduces the list of supported operating systems to the ones that we test here.
Just checking you agree with this.

**Comment by josegonzalez** [comment]
Isn't Debian 9 Stable or something? I'm happy to drop upstream in the next release if we have good reasoning we can document :)

**Comment by ltalirz** [comment]
Well, it seems the nginx repository has dropped it (just like ubuntu 16.04)

```
  TASK [nginxinc.nginx : (Debian/Ubuntu) Configure NGINX repository] *************
  failed: [instance] (item=deb [arch=amd64] https://nginx.org/packages/mainline/debian/ stretch nginx) => {"ansible_loop_var": "item", "changed": false, "item": "deb [arch=amd64] https://nginx.org/packages/mainline/debian/ stretch nginx", "msg": "Failed to update apt cache: E:The repository 'https://nginx.org/packages/mainline/debian stretch Release' does not have a Release file."}
  failed: [instance] (item=deb-src https://nginx.org/packages/mainline/debian/ stretch nginx) => {"ansible_loop_var": "item", "changed": false, "item": "deb-src https://nginx.org/packages/mainline/debian/ stretch nginx", "msg": "Failed to update apt cache: E:The repository 'https://nginx.org/packages/mainline/debian stretch Release' does not have a Release file."}
```

**Comment by josegonzalez** [comment]
Can we conditionally include that recipe? I think nginx from the official repos is new enough for dokku now.

**Comment by ltalirz** [comment]
> Can we conditionally include that recipe? I think nginx from the official repos is new enough for dokku now.

Can you elaborate a bit on what you're suggesting here?
Should we have different code paths for the debian installation depending on the debian version? 
Or drop the geerlingguy.nginx role for a "manual" installation of nginx altogether?

**Comment by josegonzalez** [comment]
Drop `geerlingguy.nginx` and just install nginx normally. It's also a dependency of dokku so it gets installed anyways...

**Comment by ltalirz** [comment]
> Drop `geerlingguy.nginx` and just install nginx normally. It's also a dependency of dokku so it gets installed anyways...

Sounds good; will do this in https://github.com/dokku/ansible-dokku/pull/122

In the meanwhile, I'll merge this with the new CI checks (keeping compatibility in the role back to Ubuntu 16.04 and Debian 9) since the failing checks are preventing pushes to ansible galaxy.

**Pull request merged**
